### GENERAL SETTINGS ###

# Site settings
title: juancancela.WORK
description: "Words and bytes from Juan Cancela"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://juancancela.work"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00982B" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://ar.linkedin.com/in/juancarloscancela
  - title: twitter
    url: https://twitter.com/devtripper

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Buenos Aires, Argentina
email: cancela.juancarlos@gmail.com
tel: +54 11 5606-5555


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
personalValues:
  - valueName: Love my family
    valueQuote: Family is not an important thing. It's everything. -Michael Fox
    img: family.jpg

  - valueName: Love crafting software
    valueQuote: Software is a great combination between artistry and engineering. -Bill Gates
    img: craft.png

  - valueName: Love learning more always
    valueQuote: Live as if you were to die tomorrow. Learn as if you were to live forever. -Mahatma Gandhi
    img: learn.jpg

  - valueName: Love work with others
    valueQuote: Individual commitment to a group effort - that is what makes a team work, a company work, a society work, a civilization work. -Vince Lombardi
    img: team.jpg

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Motivated, action-oriented technology enthusiast with experience on multiple industries designing cutting-edge Web API-centric applications."

# Testimonial content. Shown on Home and About page. 
testimonial:
message: "Juan is a serious and responsible professional with excellent knowledge. Reliable and friendly, which is a pleasure to share not only the working hours."
author: Ezequiel Doménico
position: SR. Software Developer - Mercadolibre.com
